(function(){
  var root=document.querySelector('[data-adaptation-labs]'); if(!root)return;
  var vi=document.documentElement.lang==='vi';
  function adoption(){var access=+document.querySelector('#access').value,usage=+document.querySelector('#usage').value,workflow=+document.querySelector('#workflow').value,impact=Math.round((usage+workflow)/2),gap=Math.max(0,access-impact),note=gap>35?(vi?'Ưu tiên là mức độ liên quan theo vai trò và tái thiết kế quy trình—không phải thêm quyền truy cập.':'The priority is role relevance and workflow redesign—not more access.'):gap>15?(vi?'Đã có sử dụng, nhưng hỗ trợ quản lý và thiết kế hành vi lặp lại cần được củng cố.':'Usage exists, but management support and repeat-use design need attention.'):(vi?'Năng lực đang đi vào công việc. Hãy kiểm chứng thước đo kinh doanh trước khi mở rộng.':'Capability is translating into work. Test business measures before scaling.');document.querySelector('#adoptionResult').innerHTML='<strong>'+gap+(vi?' điểm chênh lệch':' point gap')+'</strong><span>'+(vi?'Truy cập ':'Access ')+access+' · '+(vi?'Sử dụng ':'Active use ')+usage+' · '+(vi?'Thay đổi quy trình ':'Workflow change ')+workflow+' · '+(vi?'Tác động chỉ báo ':'Indicative impact ')+impact+'</span><p>'+note+'</p>'}
  ['access','usage','workflow'].forEach(function(id){document.querySelector('#'+id).addEventListener('input',adoption)});adoption();
  var tasks=root.querySelectorAll('[data-task]');tasks.forEach(function(el){el.addEventListener('change',function(){var counts={ai:0,hybrid:0,human:0};tasks.forEach(function(t){counts[t.value]++});document.querySelector('#marketingResult').innerHTML='<strong>'+counts.hybrid+' human + AI workflows</strong><span>AI '+counts.ai+' · Human + AI '+counts.hybrid+' · Human '+counts.human+'</span><p>This is a design prompt, not a workforce-reduction forecast. Examine decision rights, quality control and agency ownership next.</p>'})});tasks[0].dispatchEvent(new Event('change'));
  document.querySelector('#mirrorRun').addEventListener('click',function(){var text=document.querySelector('#mirrorText').value.trim();document.querySelector('#mirrorResult').innerHTML=text?'<strong>Prototype signal map</strong><span>Category clarity · Narrative consistency · Source authority · Information gaps</span><p>This browser-only prototype does not query an AI system. Use the entered narrative to identify which claims require authoritative public evidence.</p>':'<strong>Add a public narrative first.</strong><p>No live AI query is performed.</p>'});
  document.querySelector('#agencyRun').addEventListener('click',function(){var selected=[].slice.call(root.querySelectorAll('[name=agency]:checked')).map(function(x){return x.value});document.querySelector('#agencyResult').innerHTML='<strong>'+selected.length+' partner categories mapped</strong><span>'+ (selected.join(' · ')||'No categories selected')+'</span><p>'+(selected.length>4?'Examine overlap and decision ownership before considering consolidation.':'Look for missing specialist capability and unclear orchestration—not automatic cost cutting.')+'</p>'});
  root.addEventListener('click',function(e){if(e.target.matches('button,[type=checkbox],[type=range],select'))window.dispatchEvent(new CustomEvent('bh:analytics',{detail:{event:'lab_interaction',lab:e.target.closest('.adaptation-lab').dataset.lab}}))});
})();
