(function(){
  var root=document.querySelector('[data-adaptation-labs]'); if(!root)return;
  var vi=document.documentElement.lang==='vi';
  function adoption(){var access=+document.querySelector('#access').value,usage=+document.querySelector('#usage').value,workflow=+document.querySelector('#workflow').value,impact=Math.round((usage+workflow)/2),gap=Math.max(0,access-impact),note=gap>35?(vi?'Ưu tiên là mức độ liên quan theo vai trò và tái thiết kế quy trình—không phải thêm quyền truy cập.':'The priority is role relevance and workflow redesign—not more access.'):gap>15?(vi?'Đã có sử dụng, nhưng hỗ trợ quản lý và thiết kế hành vi lặp lại cần được củng cố.':'Usage exists, but management support and repeat-use design need attention.'):(vi?'Năng lực đang đi vào công việc. Hãy kiểm chứng thước đo kinh doanh trước khi mở rộng.':'Capability is translating into work. Test business measures before scaling.');document.querySelector('#adoptionResult').innerHTML='<strong>'+gap+(vi?' điểm chênh lệch':' point gap')+'</strong><span>'+(vi?'Truy cập ':'Access ')+access+' · '+(vi?'Sử dụng ':'Active use ')+usage+' · '+(vi?'Thay đổi quy trình ':'Workflow change ')+workflow+' · '+(vi?'Tác động chỉ báo ':'Indicative impact ')+impact+'</span><p>'+note+'</p>'}
  ['access','usage','workflow'].forEach(function(id){document.querySelector('#'+id).addEventListener('input',adoption)});adoption();
  var tasks=root.querySelectorAll('[data-task]');tasks.forEach(function(el){el.addEventListener('change',function(){var counts={ai:0,hybrid:0,human:0};tasks.forEach(function(t){counts[t.value]++});document.querySelector('#marketingResult').innerHTML=vi?'<strong>'+counts.hybrid+' quy trình Con người + AI</strong><span>AI '+counts.ai+' · Con người + AI '+counts.hybrid+' · Con người '+counts.human+'</span><p>Đây là gợi ý thiết kế, không phải dự báo cắt giảm nhân sự. Bước tiếp theo là xem xét quyền ra quyết định, kiểm soát chất lượng và quyền sở hữu agency.</p>':'<strong>'+counts.hybrid+' human + AI workflows</strong><span>AI '+counts.ai+' · Human + AI '+counts.hybrid+' · Human '+counts.human+'</span><p>This is a design prompt, not a workforce-reduction forecast. Examine decision rights, quality control and agency ownership next.</p>'})});tasks[0].dispatchEvent(new Event('change'));
  document.querySelector('#mirrorRun').addEventListener('click',function(){var text=document.querySelector('#mirrorText').value.trim();document.querySelector('#mirrorResult').innerHTML=text?(vi?'<strong>Bản đồ tín hiệu nguyên mẫu</strong><span>Độ rõ danh mục · Tính nhất quán câu chuyện · Thẩm quyền nguồn · Khoảng trống thông tin</span><p>Nguyên mẫu trong trình duyệt không truy vấn hệ thống AI. Hãy dùng nội dung đã nhập để xác định tuyên bố nào cần bằng chứng công khai có thẩm quyền.</p>':'<strong>Prototype signal map</strong><span>Category clarity · Narrative consistency · Source authority · Information gaps</span><p>This browser-only prototype does not query an AI system. Use the entered narrative to identify which claims require authoritative public evidence.</p>'):(vi?'<strong>Hãy thêm nội dung công khai trước.</strong><p>Không có truy vấn AI trực tiếp.</p>':'<strong>Add a public narrative first.</strong><p>No live AI query is performed.</p>')});
  document.querySelector('#agencyRun').addEventListener('click',function(){var selected=[].slice.call(root.querySelectorAll('[name=agency]:checked')).map(function(x){return x.value});document.querySelector('#agencyResult').innerHTML=vi?'<strong>Đã lập bản đồ '+selected.length+' nhóm đối tác</strong><span>'+ (selected.join(' · ')||'Chưa chọn nhóm nào')+'</span><p>'+(selected.length>4?'Xem xét phần chồng chéo và quyền ra quyết định trước khi cân nhắc hợp nhất.':'Tìm năng lực chuyên môn còn thiếu và cách điều phối chưa rõ—không mặc định là cắt giảm chi phí.')+'</p>':'<strong>'+selected.length+' partner categories mapped</strong><span>'+ (selected.join(' · ')||'No categories selected')+'</span><p>'+(selected.length>4?'Examine overlap and decision ownership before considering consolidation.':'Look for missing specialist capability and unclear orchestration—not automatic cost cutting.')+'</p>'});
  root.addEventListener('click',function(e){if(e.target.matches('button,[type=checkbox],[type=range],select'))window.dispatchEvent(new CustomEvent('bh:analytics',{detail:{event:'lab_interaction',lab:e.target.closest('.adaptation-lab').dataset.lab}}))});
})();
