(function () {
  function $(s) { return document.querySelector(s); }
  document.querySelectorAll('.tool-tab').forEach(function (tab) { tab.addEventListener('click', function () { document.querySelectorAll('.tool-tab,.tool-panel').forEach(function (x) { x.classList.remove('active'); }); tab.classList.add('active'); $('[data-panel="' + tab.dataset.tab + '"]').classList.add('active'); }); });

  $('#signalRun').addEventListener('click', function () {
    var text = $('#signalText').value.trim(); if (!text) { $('#signalTitle').textContent = 'Add your homepage message first.'; return; }
    var lower = text.toLowerCase(), score = 24, notes = [];
    if (/for |leaders|founders|business|teams|brands|companies|executives/.test(lower)) { score += 18; notes.push('Audience signal is visible.'); } else notes.push('Name the audience more explicitly.');
    if (/help|build|grow|turn|improve|reduce|increase|transform|scale|create/.test(lower)) { score += 18; notes.push('An intended outcome is present.'); } else notes.push('State what changes for the client.');
    if (/\d|years|projects|clients|proven|experience|results/.test(lower)) { score += 20; notes.push('Credibility is supported by evidence.'); } else notes.push('Add a concrete proof point.');
    if (text.length >= 80 && text.length <= 420) { score += 12; notes.push('Message has useful substance without overload.'); } else notes.push('Tighten the message into one focused argument.');
    if (/because|unlike|only|without|not just|point of view/.test(lower)) { score += 8; notes.push('A point of view creates distinction.'); } else notes.push('Clarify what you believe that competitors may not.');
    score = Math.min(100, score); $('#signalScore').textContent = score; $('#signalTitle').textContent = score >= 78 ? 'The signal is commercially clear.' : score >= 58 ? 'The signal is visible, but not yet sharp.' : 'The buyer has to work too hard.'; $('#signalResults').innerHTML = notes.map(function (n) { return '<li>' + n + '</li>'; }).join('');
  });

  $('#readinessRun').addEventListener('click', function () { var vals = Array.from(document.querySelectorAll('.readiness-input')).map(function (x) { return Number(x.value); }); var total = Math.round(vals.reduce(function (a,b) { return a+b; },0) / 25 * 100); var stage = total < 40 ? 'Exploring' : total < 60 ? 'Experimenting' : total < 80 ? 'Operationalising' : 'Scaling'; $('#readinessScore').textContent = total; $('#readinessStage').textContent = stage + ': focus on the weakest operating condition.'; var names=['Strategy','Data','People','Governance','Adoption']; $('#readinessResults').innerHTML = vals.map(function(v,i){return '<li>'+names[i]+': '+v+'/5'+(v<=2?' — priority gap':'')+'</li>';}).join(''); });

  var selected = ''; document.querySelectorAll('#complianceOptions .tool-option').forEach(function (b) { b.addEventListener('click', function () { selected=b.dataset.choice; document.querySelectorAll('#complianceOptions .tool-option').forEach(function(x){x.classList.remove('selected');}); b.classList.add('selected'); }); });
  $('#complianceRun').addEventListener('click', function () { var data={speed:[35,30,80,25,'Deletion alone may not remove retained copies, document the incident or satisfy notification duties.'],control:[85,90,58,88,'The strongest first move balances containment, evidence, accountable escalation and future prevention.'],ban:[72,55,20,15,'A blanket ban may contain immediate use but usually drives experimentation underground and prevents responsible learning.']}[selected]; if(!data){$('#complianceResult').innerHTML='<li>Select a response first.</li>';return;} ['risk','trust','speed','learning'].forEach(function(k,i){$('#'+k+'Score').textContent=data[i]+'/100';}); $('#complianceResult').innerHTML='<li>'+data[4]+'</li><li>Next: define approved tools, data classifications, escalation paths and practical staff training.</li>'; });

  $('#teamRun').addEventListener('click', function () { var c=$('#teamChallenge').value, map={growth:['Strategy Lead','Market & Customer Research Specialist','Commercial / Operating Advisor'],ai:['AI Transformation Lead','Data Privacy & Compliance Expert','Change & Capability Partner'],trust:['Compliance & Audit Expert','Data Privacy / Legal Counsel','AI Governance & Training Lead'],leader:['Executive Brand Strategist','Editorial & Content Partner','Media / Speaking Specialist'],commerce:['E-commerce Strategy Lead','Marketplace & Performance Specialist','Fulfilment / Market Compliance Partner']}; $('#teamTitle').textContent=$('#teamStage').value; $('#teamResults').innerHTML=map[c].map(function(x,i){return '<li>'+(i===0?'Core: ':'Specialist: ')+x+'</li>';}).join('')+'<li>Commercial model: advisory fee + separately approved third-party costs.</li>'; });
})();
