(function () {
  var vi = document.documentElement.lang === 'vi';
  function t(en, vn) { return vi ? vn : en; }
  function $(s) { return document.querySelector(s); }
  document.querySelectorAll('.tool-tab').forEach(function (tab) { tab.addEventListener('click', function () { document.querySelectorAll('.tool-tab,.tool-panel').forEach(function (x) { x.classList.remove('active'); }); tab.classList.add('active'); $('[data-panel="' + tab.dataset.tab + '"]').classList.add('active'); }); });

  var signalRun = $('#signalRun'); if (signalRun) signalRun.addEventListener('click', function () {
    var text = $('#signalText').value.trim(); if (!text) { $('#signalTitle').textContent = t('Add your homepage message first.','Hãy thêm thông điệp trang chủ trước.'); return; }
    var lower = text.toLowerCase(), score = 24, notes = [];
    if (/for |leaders|founders|business|teams|brands|companies|executives|dành cho|doanh nghiệp|lãnh đạo|đội ngũ/.test(lower)) { score += 18; notes.push(t('Audience signal is visible.','Đối tượng đã được thể hiện.')); } else notes.push(t('Name the audience more explicitly.','Nêu đối tượng cụ thể hơn.'));
    if (/help|build|grow|turn|improve|reduce|increase|transform|scale|create|giúp|xây dựng|tăng trưởng|cải thiện|chuyển đổi|mở rộng/.test(lower)) { score += 18; notes.push(t('An intended outcome is present.','Kết quả mong muốn đã được thể hiện.')); } else notes.push(t('State what changes for the client.','Nêu rõ điều gì sẽ thay đổi cho khách hàng.'));
    if (/\d|years|projects|clients|proven|experience|results|năm|dự án|khách hàng|kinh nghiệm|kết quả/.test(lower)) { score += 20; notes.push(t('Credibility is supported by evidence.','Độ tin cậy có bằng chứng hỗ trợ.')); } else notes.push(t('Add a concrete proof point.','Thêm một bằng chứng cụ thể.'));
    if (text.length >= 80 && text.length <= 420) { score += 12; notes.push(t('Message has useful substance without overload.','Thông điệp đủ nội dung mà không quá tải.')); } else notes.push(t('Tighten the message into one focused argument.','Tinh gọn thông điệp thành một luận điểm tập trung.'));
    if (/because|unlike|only|without|not just|point of view|bởi vì|không chỉ|khác với|quan điểm/.test(lower)) { score += 8; notes.push(t('A point of view creates distinction.','Quan điểm riêng tạo nên khác biệt.')); } else notes.push(t('Clarify what you believe that competitors may not.','Làm rõ điều bạn tin nhưng đối thủ có thể không tin.'));
    score = Math.min(100, score); $('#signalScore').textContent = score; $('#signalTitle').textContent = score >= 78 ? t('The signal is commercially clear.','Tín hiệu thương mại đã rõ.') : score >= 58 ? t('The signal is visible, but not yet sharp.','Tín hiệu đã có nhưng chưa đủ sắc.') : t('The buyer has to work too hard.','Khách hàng đang phải tự suy luận quá nhiều.'); $('#signalResults').innerHTML = notes.map(function (n) { return '<li>' + n + '</li>'; }).join('');
  });

  var readinessRun = $('#readinessRun'); if (readinessRun) readinessRun.addEventListener('click', function () { var vals = Array.from(document.querySelectorAll('.readiness-input')).map(function (x) { return Number(x.value); }); var total = Math.round(vals.reduce(function (a,b) { return a+b; },0) / 25 * 100); var stage = total < 40 ? t('Exploring','Đang khám phá') : total < 60 ? t('Experimenting','Đang thử nghiệm') : total < 80 ? t('Operationalising','Đang đưa vào vận hành') : t('Scaling','Đang mở rộng'); $('#readinessScore').textContent = total; $('#readinessStage').textContent = stage + t(': focus on the weakest operating condition.',': ưu tiên điều kiện vận hành yếu nhất.'); var names=vi?['Chiến lược','Dữ liệu','Con người','Quản trị','Ứng dụng']:['Strategy','Data','People','Governance','Adoption']; $('#readinessResults').innerHTML = vals.map(function(v,i){return '<li>'+names[i]+': '+v+'/5'+(v<=2?t(' — priority gap',' — khoảng cách ưu tiên'):'')+'</li>';}).join(''); });

  var selected = ''; document.querySelectorAll('#complianceOptions .tool-option').forEach(function (b) { b.addEventListener('click', function () { selected=b.dataset.choice; document.querySelectorAll('#complianceOptions .tool-option').forEach(function(x){x.classList.remove('selected');}); b.classList.add('selected'); }); });
  var complianceRun = $('#complianceRun'); if (complianceRun) complianceRun.addEventListener('click', function () { var data={speed:[35,30,80,25,t('Deletion alone may not remove retained copies, document the incident or satisfy notification duties.','Chỉ xóa nội dung có thể không loại bỏ bản sao đã lưu, ghi nhận sự cố hoặc đáp ứng nghĩa vụ thông báo.')],control:[85,90,58,88,t('The strongest first move balances containment, evidence, accountable escalation and future prevention.','Bước đầu tốt nhất cân bằng giữa khoanh vùng, lưu bằng chứng, báo cáo đúng trách nhiệm và phòng ngừa tái diễn.')],ban:[72,55,20,15,t('A blanket ban may contain immediate use but usually drives experimentation underground and prevents responsible learning.','Lệnh cấm toàn diện có thể ngăn sử dụng tức thời nhưng thường đẩy thử nghiệm vào vùng không kiểm soát và cản trở việc học hỏi có trách nhiệm.')]}[selected]; if(!data){$('#complianceResult').innerHTML='<li>'+t('Select a response first.','Hãy chọn một phương án trước.')+'</li>';return;} ['risk','trust','speed','learning'].forEach(function(k,i){$('#'+k+'Score').textContent=data[i]+'/100';}); $('#complianceResult').innerHTML='<li>'+data[4]+'</li><li>'+t('Next: define approved tools, data classifications, escalation paths and practical staff training.','Tiếp theo: xác định công cụ được phép, phân loại dữ liệu, quy trình báo cáo và đào tạo thực tế cho nhân viên.')+'</li>'; });

  var teamRun = $('#teamRun'); if (teamRun) teamRun.addEventListener('click', function () { var c=$('#teamChallenge').value, map=vi?{growth:['Cố vấn chiến lược','Chuyên gia nghiên cứu thị trường và khách hàng','Cố vấn thương mại và vận hành'],ai:['Chuyên gia chuyển đổi AI','Chuyên gia bảo mật dữ liệu và tuân thủ','Đối tác quản trị thay đổi và năng lực'],trust:['Chuyên gia kiểm toán và tuân thủ','Cố vấn pháp lý và bảo mật dữ liệu','Chuyên gia quản trị AI và đào tạo'],leader:['Chiến lược gia thương hiệu lãnh đạo','Đối tác biên tập và nội dung','Chuyên gia truyền thông và diễn thuyết'],commerce:['Cố vấn chiến lược thương mại điện tử','Chuyên gia sàn thương mại điện tử và tiếp thị hiệu suất','Đối tác vận hành đơn hàng và tuân thủ thị trường']}:{growth:['Strategy Lead','Market & Customer Research Specialist','Commercial / Operating Advisor'],ai:['AI Transformation Lead','Data Privacy & Compliance Expert','Change & Capability Partner'],trust:['Compliance & Audit Expert','Data Privacy / Legal Counsel','AI Governance & Training Lead'],leader:['Executive Brand Strategist','Editorial & Content Partner','Media / Speaking Specialist'],commerce:['E-commerce Strategy Lead','Marketplace & Performance Specialist','Fulfilment / Market Compliance Partner']}; $('#teamTitle').textContent=$('#teamStage').options[$('#teamStage').selectedIndex].text; $('#teamResults').innerHTML=map[c].map(function(x,i){return '<li>'+t(i===0?'Core: ':'Specialist: ',i===0?'Cốt lõi: ':'Chuyên gia: ')+x+'</li>';}).join('')+'<li>'+t('Commercial model: advisory fee + separately approved third-party costs.','Mô hình thương mại: phí tư vấn + chi phí bên thứ ba được phê duyệt riêng.')+'</li>'; });
})();
