(function () {
  function $(s) { return document.querySelector(s); }
  function money(n) { return Number.isFinite(n) ? new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(n) : '—'; }
  document.querySelectorAll('.tool-tab').forEach(function (tab) { tab.addEventListener('click', function () { document.querySelectorAll('.tool-tab,.tool-panel').forEach(function (x) { x.classList.remove('active'); }); tab.classList.add('active'); $('[data-panel="'+tab.dataset.tab+'"]').classList.add('active'); }); });
  $('#profitRun').addEventListener('click', function () { var p=Number($('#price').value), c=Number($('#cogs').value), fee=p*Number($('#fee').value)/100, f=Number($('#fulfilment').value), ret=p*Number($('#returns').value)/100, ad=Number($('#adcost').value); var beforeAds=p-c-fee-f-ret, contribution=beforeAds-ad, margin=p?contribution/p*100:0, roas=beforeAds>0?p/beforeAds:0, discounted=p*.9-c-(p*.9*Number($('#fee').value)/100)-f-(p*.9*Number($('#returns').value)/100)-ad; $('#contribution').textContent=money(contribution); $('#margin').textContent=margin.toFixed(1)+'%'; $('#roas').textContent=roas.toFixed(2)+'×'; $('#cac').textContent=money(Math.max(0,beforeAds)); $('#discountProfit').textContent=money(discounted); var msg=contribution<0?'Each order currently destroys value. Fix price, costs or acquisition before scaling.':margin<15?'The operation is positive but fragile. Promotions or returns can erase the margin quickly.':'The base economics show room to test growth—provided repeat purchase and overhead also work.'; $('#profitInsight').innerHTML='<li>'+msg+'</li><li>Third-party platform, media and fulfilment costs should remain visible—not buried inside advisory fees.</li>'; });
  $('#marketRun').addEventListener('click', function () { var cat=$('#category').value, market=$('#market').value, channel=$('#channel').value, maturity=Number($('#maturity').value); var posture=maturity<=1?'Prove demand before infrastructure.':maturity===2?'Build repeatable local economics.':maturity===3?'Prepare the operating system for expansion.':'Scale selectively, with market-level controls.'; $('#marketPosture').textContent=posture; var compliance=/Health|Food/.test(cat)?'Validate product claims, registration, labels and data/privacy requirements before launch.':'Confirm product, consumer, tax, data and marketplace obligations in '+market+'.'; var channelNote=channel==='TikTok Shop'?'Design demonstration-led content and live-commerce operations, not only product pages.':channel==='Amazon'?'Model fees, reviews, fulfilment and search economics before inventory commitment.':channel==='Direct-to-consumer website'?'Plan acquisition, first-party data, trust and fulfilment as one system.':'Win search, ratings, availability and campaign economics on the digital shelf.'; $('#marketResults').innerHTML='<li><strong>Customer fit:</strong> test one priority segment and buying occasion.</li><li><strong>Channel:</strong> '+channelNote+'</li><li><strong>Localisation:</strong> adapt value, proof, price architecture and content—not just language.</li><li><strong>Compliance:</strong> '+compliance+'</li><li><strong>30–60–90:</strong> validate → launch controlled pilot → improve and scale.</li>'; });
  $('#listingRun').addEventListener('click', function () { var name=$('#productName').value.trim()||'Product', customer=$('#customer').value.trim(), feature=$('#feature').value.trim(), benefit=$('#benefit').value.trim(), proof=$('#proof').value.trim(); $('#listingBefore').textContent=name+' with '+feature+'. Buy now.'; $('#listingHeadline').textContent=benefit.charAt(0).toUpperCase()+benefit.slice(1)+'. Made easier.'; $('#listingBody').textContent=name+' is designed for '+customer+', combining '+feature+' to support '+benefit+'.'; $('#listingBullets').innerHTML='<li><strong>Built for:</strong> '+customer+'</li><li><strong>Why it works:</strong> '+feature+'</li><li><strong>Trust:</strong> '+proof+'</li><li><strong>Next:</strong> Pair the copy with demonstration, reviews and a channel-specific CTA.</li>'; });
  $('#profitRun').click(); $('#marketRun').click(); $('#listingRun').click();
})();
