(function () {
  if (location.pathname.indexOf('/vi/') < 0) return;
  var map = {
    'About':'Về chúng tôi','What We Do':'Dịch vụ','Approach':'Phương pháp','Expert Network':'Chuyên gia','Experts':'Chuyên gia','Partners':'Đối tác','Work':'Dự án','Insights':'Góc nhìn','Book a Decision Session':'Đặt lịch Decision Session','← All Labs':'← Tất cả Labs','Discuss the result':'Trao đổi về kết quả',
    'Better questions.\nSharper decisions.':'Câu hỏi tốt hơn.\nQuyết định sắc hơn.','Better questions.':'Câu hỏi tốt hơn.','Sharper decisions.':'Quyết định sắc hơn.','Four lightweight diagnostics reveal where clarity, capability, governance and specialist support may be holding the business back.':'Bốn chẩn đoán nhanh cho thấy điểm nghẽn về sự rõ ràng, năng lực, quản trị hoặc hỗ trợ chuyên môn.','Brand Signal':'Tín hiệu thương hiệu','AI Readiness':'Mức độ sẵn sàng AI','Compliance Game':'Tình huống tuân thủ','Advisory Team':'Đội ngũ tư vấn','Brand Signal Scanner':'Kiểm tra tín hiệu thương hiệu','Scan the signal':'Phân tích tín hiệu','Calculate readiness':'Tính mức độ sẵn sàng','Compliance Decision Game':'Tình huống ra quyết định Compliance','See the consequence':'Xem hệ quả','Build Your Advisory Team':'Xây dựng đội ngũ tư vấn','Assemble the team':'Đề xuất đội ngũ',
    'Growth has to work\non the spreadsheet.':'Tăng trưởng phải đứng vững\ntrên bảng tính.','Growth has to work':'Tăng trưởng phải đứng vững','on the spreadsheet.':'trên bảng tính.','Test whether the product story, unit economics and market-entry choices can support a functioning e-commerce operation—not just a launch campaign.':'Kiểm tra liệu câu chuyện sản phẩm, hiệu quả kinh tế trên từng đơn hàng và lựa chọn vào thị trường có đủ sức nâng đỡ hoạt động thương mại điện tử thật sự.','Profitability':'Hiệu quả tài chính','Market Entry':'Vào thị trường','Listing Makeover':'Tối ưu trang giới thiệu sản phẩm','Profitability Calculator':'Tính hiệu quả đơn hàng','Calculate economics':'Tính hiệu quả từng đơn hàng','Market Entry Simulator':'Mô phỏng vào thị trường','Build entry map':'Tạo bản đồ thâm nhập','Product Listing Makeover':'Tối ưu trang sản phẩm','Create the makeover':'Tạo phiên bản mới','Before':'Trước','After':'Sau',
    'Alignment is not\nthe goal.':'Đồng thuận chưa chắc\nđã là đúng hướng.','Alignment is not':'Đồng thuận chưa chắc','the goal.':'đã là đúng hướng.','Three forces govern how any group moves together: separation, alignment and cohesion. Every organisation is running some combination of them right now. Most leaders have never seen what their combination actually produces.':'Ba lực chi phối cách một tập thể chuyển động: khoảng cách, đồng hướng và gắn kết. Mỗi tổ chức đang vận hành bằng một tổ hợp khác nhau, nhưng phần lớn lãnh đạo chưa từng nhìn thấy trạng thái mà tổ hợp đó tạo ra.','The three forces':'Ba lực tác động','Separation':'Khoảng cách','Alignment':'Đồng hướng','Cohesion':'Gắn kết','Silo':'Silo','Groupthink':'Tư duy nhóm','Drift':'Trôi hướng','Coherent':'Nhất quán','The field':'Trường chuyển động','Directional order':'Mức độ đồng hướng','Dispersion':'Độ phân tán','What this produces':'Trạng thái tạo ra',
    'Bridge\nthe Gap':'Vượt qua\nkhoảng cách','Bridge':'Vượt qua','the Gap':'khoảng cách','Ideas only create impact when they make it across.':'Ý tưởng chỉ tạo ra tác động khi vượt qua được khoảng cách.','Start the journey':'Bắt đầu hành trình','Try again':'Thử lại','Impact created':'Tác động tạo ra','Current capability':'Năng lực hiện tại','What the game is teaching':'Thông điệp của trò chơi','Transformation is a sequence, not a leap.':'Chuyển đổi là một chuỗi bước, không phải một cú nhảy.',
    'What if a brand idea could be heard?':'Nếu một ý tưởng thương hiệu có thể được nghe thấy?','Ready to play':'Sẵn sàng phát','Live lyrics':'Lời bài hát đồng bộ','Hide lyrics':'Ẩn lời bài hát','The creative brief':'Đề bài sáng tạo','Human–AI collaboration':'Hợp tác người–AI','Beyond one song':'Không chỉ một bài hát','Creative disclosure':'Công bố phương thức sáng tạo','AI-assisted original work':'Tác phẩm nguyên bản có AI hỗ trợ',
    'The signal is commercially clear.':'Tín hiệu thương mại đã rõ.','The signal is visible, but not yet sharp.':'Tín hiệu đã có, nhưng chưa đủ sắc.','The buyer has to work too hard.':'Người mua đang phải tự suy luận quá nhiều.','Add your homepage message first.':'Hãy thêm thông điệp trang chủ trước.','Exploring: focus on the weakest operating condition.':'Đang khám phá: ưu tiên điều kiện vận hành yếu nhất.','Experimenting: focus on the weakest operating condition.':'Đang thử nghiệm: ưu tiên điều kiện vận hành yếu nhất.','Operationalising: focus on the weakest operating condition.':'Đang đưa vào vận hành: ưu tiên điều kiện vận hành yếu nhất.','Scaling: focus on the weakest operating condition.':'Đang mở rộng: ưu tiên điều kiện vận hành yếu nhất.',
    'Each order currently destroys value. Fix price, costs or acquisition before scaling.':'Mỗi đơn hàng hiện đang làm mất giá trị. Hãy sửa giá, chi phí hoặc chi phí thu hút khách hàng trước khi mở rộng.','The operation is positive but fragile. Promotions or returns can erase the margin quickly.':'Mô hình đang dương nhưng còn mong manh. Khuyến mãi hoặc hoàn hàng có thể nhanh chóng xóa biên lợi nhuận.','The base economics show room to test growth—provided repeat purchase and overhead also work.':'Hiệu quả kinh tế cơ bản cho phép thử tăng trưởng, nếu tỷ lệ mua lại và chi phí quản lý chung cũng hợp lý.'
  };
  Object.assign(map, {
    'Homepage message':'Thông điệp trang chủ','Paste your headline and introduction…':'Dán tiêu đề và phần giới thiệu…','Clarity score':'Điểm rõ ràng','Your signal will appear here.':'Tín hiệu của bạn sẽ xuất hiện ở đây.','Specific audience':'Đối tượng cụ thể','Clear outcome':'Kết quả rõ ràng','Credible evidence':'Bằng chứng đáng tin','Distinct point of view':'Quan điểm khác biệt','Local prototype: text stays in your browser.':'Bản thử nghiệm cục bộ: nội dung chỉ nằm trong trình duyệt.','Rate the organisation from 1 (early) to 5 (established).':'Đánh giá tổ chức từ 1 (mới bắt đầu) đến 5 (đã thiết lập).','Business priority is clear':'Ưu tiên kinh doanh rõ ràng','Data can be used safely':'Dữ liệu có thể được sử dụng an toàn','Leaders own adoption':'Lãnh đạo chịu trách nhiệm về việc ứng dụng','Governance is practical':'Quản trị có tính thực tế','Teams can redesign work':'Đội ngũ có thể thiết kế lại công việc','Move the inputs to begin.':'Điều chỉnh các thông số để bắt đầu.','Risk control':'Kiểm soát rủi ro','Trust':'Niềm tin','Operating speed':'Tốc độ vận hành','Learning':'Khả năng học hỏi','Choose a response to see its trade-offs.':'Chọn một phản ứng để xem các đánh đổi.','Select the primary challenge.':'Chọn thách thức chính.','Business challenge':'Thách thức kinh doanh','Stage':'Giai đoạn','Suggested engagement':'Cấu trúc tư vấn đề xuất','A focused core, specialists when needed.':'Một đội ngũ nòng cốt tập trung, thêm chuyên gia khi cần.',
    'Enter values per order in the same currency.':'Nhập giá trị trên mỗi đơn hàng bằng cùng một đơn vị tiền tệ.','Selling price':'Giá bán','Cost of goods':'Giá vốn','Platform fee (%)':'Phí nền tảng (%)','Fulfilment and packaging':'Xử lý đơn hàng và đóng gói','Return / cancellation rate (%)':'Tỷ lệ hoàn / hủy (%)','Advertising cost per order':'Chi phí quảng cáo mỗi đơn','Contribution per order':'Lợi nhuận đóng góp mỗi đơn','Contribution margin':'Biên lợi nhuận đóng góp','Break-even ROAS':'ROAS hòa vốn','Maximum CAC':'CAC tối đa','Profit at 10% discount':'Lợi nhuận khi giảm giá 10%','Revenue is not the same as profitable growth.':'Doanh thu không đồng nghĩa với tăng trưởng có lợi nhuận.','Choose the commercial context to reveal a first-pass entry path.':'Chọn bối cảnh thương mại để xem lộ trình vào thị trường ban đầu.','Product category':'Ngành hàng','Target market':'Thị trường mục tiêu','Primary channel':'Kênh chính','Current readiness':'Mức độ sẵn sàng hiện tại','Recommended posture':'Định hướng đề xuất','Validate before you scale.':'Xác thực trước khi mở rộng.','Customer fit':'Mức độ phù hợp khách hàng','Channel economics':'Hiệu quả kinh tế theo kênh','Localisation':'Bản địa hóa','Compliance':'Tuân thủ','Fulfilment':'Vận hành đơn hàng','Product name':'Tên sản phẩm','Primary customer':'Khách hàng chính','Key feature':'Tính năng chính','Primary benefit':'Lợi ích chính','Proof or trust signal':'Bằng chứng / tín hiệu tin cậy',
    'Original music developed through human judgement, brand strategy and AI tạo sinh. Not a prompt-and-publish exercise — a creative system shaped through direction, selection and refinement.':'Âm nhạc nguyên bản được phát triển qua khả năng đánh giá của con người, chiến lược thương hiệu và AI tạo sinh. Đây không phải nhập câu lệnh rồi đăng, mà là một hệ thống sáng tạo được định hướng, lựa chọn và tinh chỉnh.','Read the meaning as it moves.':'Đọc ý nghĩa theo nhịp bài hát.','Lyrics are synchronized with MASTER A. Select a line to jump to that moment.':'Lời bài hát được đồng bộ với MASTER A. Chọn một dòng để chuyển đến thời điểm tương ứng.','AI expanded the possibilities. Năng lực đánh giá thương hiệu shaped the result.':'AI mở rộng khả năng. Năng lực đánh giá thương hiệu định hình kết quả.','One idea.\nMany usable forms.':'Một ý tưởng.\nNhiều hình thức sử dụng.','Ready to make a brand idea people can feel?':'Sẵn sàng tạo một ý tưởng thương hiệu mà mọi người có thể cảm nhận?'
  });
  function translate(root) {
    var walker = document.createTreeWalker(root || document.body, NodeFilter.SHOW_TEXT), node;
    while ((node = walker.nextNode())) {
      var raw = node.nodeValue, key = raw.trim();
      if (map[key]) node.nodeValue = raw.replace(key, map[key]);
    }
  }
  translate(document.body);
  new MutationObserver(function(changes){changes.forEach(function(c){c.addedNodes.forEach(function(n){if(n.nodeType===1)translate(n);else if(n.nodeType===3){var k=n.nodeValue.trim();if(map[k])n.nodeValue=n.nodeValue.replace(k,map[k]);}});});}).observe(document.body,{subtree:true,childList:true,characterData:true});
  document.querySelectorAll('a[href]').forEach(function (a) {
    var h = a.getAttribute('href');
    if (!h || h.charAt(0) === '#' || h.indexOf('http') === 0 || h.indexOf('mailto:') === 0) return;
    var parts = h.split('?'), file = parts[0];
    var translated = ['index.html','about.html','what-we-do.html','approach.html','experts.html','partners.html','work.html','labs.html','insights.html','radio.html','game.html','alignment-lab.html','advisory-lab.html','commerce-lab.html','decision-session.html','contact.html'];
    if (translated.indexOf(file) >= 0) a.setAttribute('href', 'vi/' + file + (parts[1] ? '?' + parts[1] : ''));
  });
  var nav = document.querySelector('nav');
  if (nav && !nav.querySelector('.lang-switch')) {
    var cta = nav.querySelector('.nav-cta');
    var sw = document.createElement('div'); sw.className = 'lang-switch'; sw.innerHTML = '<a href="' + location.pathname.replace('/vi/','/') + '">EN</a><strong>VI</strong>';
    nav.insertBefore(sw, cta || nav.lastChild);
  }
})();
